// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppBar from "./components/AppBar";

export const playfair =localFont({
  src: "./fonts/PlayfairDisplay-VariableFont_wght.ttf",
  
  weight: "400 500 600 700 800"
  
})
export const greatVibes =localFont({
  src: "./fonts/GreatVibes-Regular.ttf",
  
  weight: "400 500 600 700 800"
  
})


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
           <head>
      <title>YMPH</title>
  {/* <title>{metadata.title ?? "Default Title"}</title> */}
  {/* <meta  name="description" content={metadata.description ?? "Default description"} /> */}
</head>
      <body
        className={`${playfair.className} antialiased`}
      >
        <AppBar/>
        {children}
      </body>
    </html>
  );
}
